# -*- coding: utf-8 -*-
"""Face Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1skL1C-Fd-BQep8SnfTm26Yt9DfMglKbO
"""

from google.colab import drive
drive.mount('/content/drive')
!pip install keras-facenet mtcnn scikit-learn tensorflow
!pip install lz4

import os
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import matplotlib.pyplot as plt
import cv2
import requests
import tarfile
import random
import pickle
import zipfile
from keras_facenet import FaceNet
from sklearn.preprocessing import Normalizer
from mtcnn import MTCNN
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from tqdm.notebook import tqdm

zip_path = "archive.zip"
extract_path = "/content"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

dataset_path = "/content/lfw-deepfunneled/lfw-deepfunneled"
print("Dataset path:", dataset_path)
print("Number of people:", len(os.listdir(dataset_path)))

class FaceRecognitionSystem:
  def __init__(self):

    self.detector = MTCNN()
    self.embedder = FaceNet()
    self.normalizer = Normalizer(norm='l2')

    self.required_size = (160,160)
    self.embeddings = []
    self.labels = []
    self.le = LabelEncoder()
    self.classifier = SVC( kernel='rbf', C=10, gamma='scale', probability=True)

  def _extract_face(self, image):
    faces = self.detector.detect_faces(image)
    if not faces:
      return None

    x1, y1, width, height = faces[0]['box']
    x2, y2 = x1 + width, y1 + height

    face = image[y1:y2,x1:x2]
    face = cv2.resize(face, self.required_size)
    return face

  def _get_embedding(self, face):
    face = face.astype('float32')
    embedding = self.embedder.embeddings(np.expand_dims(face, axis=0))[0]
    return embedding

  def process_dataset(self, dataset_path, max_samples_per_person=20):
    person_samples = {}

    for person_name in os.listdir(dataset_path):
      person_dir = os.path.join(dataset_path, person_name)
      if os.path.isdir(person_dir):
        images = [f for f in os.listdir(person_dir)
                  if f.endswith(('.jpg', '.jpeg', '.png'))]
        if len(images) >= 15:
          person_samples[person_name] = images[:max_samples_per_person] # Limit to max_samples_per_person
    print(f"Found {len(person_samples)} people with sufficient samples")

    for person_name, images in tqdm(person_samples.items(), desc="Processing people"):
      successful_embeddings = 0
      for image_name in images:
        try:
          image_path = os.path.join(dataset_path, person_name, image_name)
          image = cv2.imread(image_path)
          if image is None:
            continue

          image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
          face = self._extract_face(image)

          if face is not None:
            embedding = self._get_embedding(face)
            self.embeddings.append(embedding)
            self.labels.append(person_name)
            successful_embeddings +=1
        except Exception as e:
          print(f"Error Processing {image_path}: {str(e)}")

      if successful_embeddings > 0:
        print(f"Processed {successful_embeddings} images for {person_name}")

  def train_classifier(self):
    if len(self.embeddings) == 0:
      print("No embeddings to train on!")
      return None

    X = np.array(self.embeddings)
    X = self.normalizer.fit_transform(X)

    encoded_labels = self.le.fit_transform(self.labels)

    X_train, X_test, y_train, y_test = train_test_split(X,encoded_labels,test_size=0.2,stratify=encoded_labels,random_state=42)
    self.classifier.fit(X_train, y_train)

    y_pred = self.classifier.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    return {"accuracy": accuracy, "report": classification_report(y_test, y_pred), "y_train": y_train, "y_test": y_test, "y_pred": y_pred}

def plot_Results(results):
  if results is None:
    print("No results to plot!")
    return

  plt.figure(figsize=(15,5))

  plt.subplot(1, 2, 1)
  plt.title('Training Data Distribution')
  unique, counts = np.unique(results['y_train'], return_counts = True)
  plt.bar(unique[:10], counts[:10])
  plt.xlabel("Person ID (First 10)")
  plt.ylabel("Number of samples")

  plt.subplot(1,2,2)
  plt.title(f"Model Accuracy: {results['accuracy']:.2%}")
  cm = tf.math.confusion_matrix(results['y_test'], results['y_pred'])
  plt.imshow(cm, interpolation = 'nearest', cmap=plt.cm.Blues)
  plt.colorbar()
  plt.xlabel("Predicted Label")
  plt.ylabel("True Label")

  plt.tight_layout()
  plt.show()

!pip install -U lz4

import lz4
import joblib
import joblib.compressor

print("LZ4 version:", lz4.__version__)
print("Joblib version:", joblib.__version__)
print("Joblib sees lz4:", joblib.compressor.lz4)

try:
  print("Initalizing Face Recognition System...")
  face_System = FaceRecognitionSystem()

  print("Processing dataset...")
  dataset_path = '/content/lfw-deepfunneled/lfw-deepfunneled'
  face_System.process_dataset(dataset_path, max_samples_per_person=20)

  print("Training classifier on", len(face_System.embeddings)," samples...")
  results = face_System.train_classifier()
  if  results is not None:
    print("Plotting results...")
    plot_Results(results)

    y_true = face_System.le.inverse_transform(results['y_test'])
    y_pred = face_System.le.inverse_transform(results['y_pred'])

    print("\nClassification Report:")
    print(classification_report(y_true, y_pred))

    save_path = "/content/drive/MyDrive/face_recognition_model.pkl"
    if os.path.exists('/content/drive'):
      import pickle
      model_data = {'classifier': face_System.classifier,'label_encoder': face_System.le,'normalizer': face_System.normalizer}
      with open(save_path, 'wb') as f:
        pickle.dump(model_data, f)
      print(f"Model saved to {save_path}")
    else:
      print(f"Model saves to Google Drive: {save_path}")
except Exception as e:
  print(f"An error occurred: {str(e)}")
  raise



class FaceRecoginationDemo:
  def __init__(self, model_path):
    with open(model_path, 'rb') as f:
      model_data = pickle.load(f)

    self.classifier = model_data['classifier']
    self.le = model_data['label_encoder']
    self.normalizer = model_data['normalizer']
    self.detector = MTCNN()

    self.embedder = FaceNet()
    self.required_size = (160,160)
  def process_image(self, image):
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    faces = self.detector.detect_faces(rgb_image)

    if not faces:
      return None, None

    x1, y1, width, height = faces[0]['box']
    x2, y2 = x1 + width, y1 + height

    face = rgb_image[y1:y2, x1:x2]
    face_resized = cv2.resize(face, self.required_size)

    embedding = self.embedder.embeddings(
    np.expand_dims(face_resized.astype('float32'), axis=0))[0]

    embedding = self.normalizer.transform([embedding])[0]
    return embedding, (x1, y1, x2, y2)

  def predict(self, image):
    embedding, face_box = self.process_image(image)
    if embedding is None:
      return None, None, None

    pred_proba = self.classifier.predict_proba([embedding])[0]
    pred_class = np.argmax(pred_proba)
    confidence = pred_proba[pred_class]
    pred_label = self.le.inverse_transform([pred_class])[0]

    if confidence < 0.05:
     pred_label = "Unknown"

    return pred_label, confidence, face_box

def get_random_test_images(dataset_path, trained_people, num_images=5):

    selected_people = random.sample(list(trained_people),min(num_images, len(trained_people)))

    test_images = []
    for person in selected_people:
        person_dir = os.path.join(dataset_path, person)
        images = [f for f in os.listdir(person_dir) if f.endswith(('.jpg', '.jpeg', '.png'))]
        image_path = os.path.join(person_dir,random.choice(images))

        image = cv2.imread(image_path)
        if image is not None:
            test_images.append((person, image))

    return test_images

def display_results(test_images, predoctions):
  plt.figure(figsize=(20, 4))
  for i, ((true_name, image), (pred_name, confidence, face_box)) in enumerate(zip(test_images, predictions)):
    plt.subplot(1, len(test_images), i+1)

    image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    if face_box:
      x1, y1, x2, y2 = face_box
      cv2.rectangle(image_rgb, (x1, y1), (x2, y2), (0, 255, 0), 2)

    plt.imshow(image_rgb)
    if pred_name is None:
      result_text = f"True: {true_name}\nNo face detected"
    else:
      result_text = f"True: {true_name}\nPred: {pred_name}\nConf: {confidence:.2%}"
    plt.title(result_text, fontsize=10)
    plt.axis('off')

  plt.tight_layout()
  plt.show()

try:
    drive.mount('/content/drive')
    model_path = '/content/drive/MyDrive/face_recognition_model.pkl'
    dataset_path = '/content/lfw-deepfunneled/lfw-deepfunneled'

    print("Initializing demo system...")
    demo_system = FaceRecoginationDemo(model_path)

    print("Getting random test images...")
    test_images = get_random_test_images(dataset_path,demo_system.le.classes_ ,num_images=25)

    print("Making predictions...")
    predictions = []

    for _, image in test_images:
        pred_name, confidence, face_box = demo_system.predict(image)
        predictions.append((pred_name, confidence, face_box))

    print("Displaying results...")
    display_results(test_images, predictions)

    correct_predictions = sum(1 for (true_name, _), (pred_name, _, _)
                              in zip(test_images, predictions)
                              if pred_name is not None and true_name == pred_name )
    print(f"Correct predictions: {correct_predictions}/{len(test_images)}")

    for (true_name,_), (pred_name, confidence, _) in zip(test_images, predictions):
      if pred_name is None:
        print(f"True: {true_name:<20} No face detected")
      else:
        status = "Correct" if true_name == pred_name else "Incorrect"
        print(f"{status}: True: {true_name:<20} Predicted: {pred_name:<20} Confidence: {confidence:.2%}")

    total_images = len(test_images)
    accuracy = correct_predictions / total_images

    print(f"Accuracy: {accuracy:.2%}")

except Exception as e:
    print(f"An error occurred: {str(e)}")
    raise

print(f"Model Accuracy: {results['accuracy']:.2%}")

trained_people = set(demo_system.le.classes_)

for true_name, _ in test_images:
    print(
        f"{true_name} -> {'TRAINED' if true_name in trained_people else 'NOT TRAINED'}"
    )

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

print("="*60)
print("MODEL PERFORMANCE EVALUATION")
print("="*60)

# Overall Accuracy
accuracy = accuracy_score(results['y_test'], results['y_pred'])
print(f"\nAccuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")

# Precision, Recall, F1 Score
precision = precision_score(results['y_test'],results['y_pred'],average='weighted',zero_division=0)

recall = recall_score(results['y_test'],results['y_pred'],average='weighted',zero_division=0)

f1 = f1_score(results['y_test'],results['y_pred'],average='weighted',zero_division=0)

print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1-Score:  {f1:.4f}")

print("\n" + "="*60)
print("CLASSIFICATION REPORT")
print("="*60)

# Convert labels back to names
y_true_names = face_System.le.inverse_transform(results['y_test'])
y_pred_names = face_System.le.inverse_transform(results['y_pred'])

print(classification_report(y_true_names,y_pred_names,zero_division=0))

print("\n" + "="*60)
print("CONFUSION MATRIX")
print("="*60)

cm = confusion_matrix(results['y_test'], results['y_pred'])
print(cm)